### ISSUE TITLE
Number format exception when using number suffixes.

### ISSUE THREAD

**Issue by Fernthedev** [Tabuu/PermissionShopZ#7]
Would like to report that when using the config values: 
```yaml
# DESCRIPTION:  Whether or not zeros in the price should be replaced with their corresponding suffix.
# FORMAT:       Boolean
# NOTE:         The suffixes can be configured below.
UseNumberSuffix: true

# DESCRIPTION:  Suffixes per zero count.
# FORMAT:       'zero count': 'suffix'
NumberSuffixes:
  3: "k"
  6: "M"
  9: "B"
``` 
or as the default config has
```yaml
# DESCRIPTION:  Whether or not zeros in the price should be replaced with their corresponding suffix.
# FORMAT:       Boolean
# NOTE:         The suffixes can be configured below.
UseNumberSuffix: true

# DESCRIPTION:  Suffixes per zero count.
# FORMAT:       'zero count': 'suffix'
NumberSuffixes:
  '3': 'k'
  '6': 'M'
  '9': 'B'
```
the command fails and the console shows this error:
```
[23:17:37 WARN]: java.lang.NumberFormatException: For input string: "NumberSuffixes.UseNumberSuffix"
[23:17:37 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[23:17:37 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:652)
[23:17:37 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:770)
[23:17:37 WARN]:        at nl.tabuu.permissionshopz.util.NumberFormat.suffixFormat(NumberFormat.java:20)
[23:17:37 WARN]:        at nl.tabuu.permissionshopz.data.Perk.getReplacements(Perk.java:68)
[23:17:37 WARN]:        at nl.tabuu.permissionshopz.gui.ShopInterface.createPerkItem(ShopInterface.java:131)
[23:17:37 WARN]:        at nl.tabuu.permissionshopz.gui.ShopInterface.onDraw(ShopInterface.java:114)
[23:17:37 WARN]:        at nl.tabuu.tabuucore.inventory.ui.InventoryUI.open(InventoryUI.java:40)
[23:17:37 WARN]:        at nl.tabuu.permissionshopz.command.PermissionShopCommand.shop(PermissionShopCommand.java:41)
[23:17:37 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:17:37 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:17:37 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:17:37 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[23:17:37 WARN]:        at nl.tabuu.tabuucore.command.CommandRegister$1.onCommand(CommandRegister.java:174)
[23:17:37 WARN]:        at nl.tabuu.tabuucore.command.Command.execute(Command.java:99)
[23:17:37 WARN]:        at nl.tabuu.tabuucore.command.Command.onCommand(Command.java:120)
[23:17:37 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:17:37 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:17:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils$$Lambda$6444/00000000892D2F60.run(Unknown Source)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:17:37 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3118/000000002DFAB190.run(Unknown Source)
[23:17:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:836)
```

I am using TabuuCore 2.0.0 and PermissionShopZ 1.0.0
I have reset config.yml and lang.yml

**Comment by Tabuu** [comment]
The issue has been resolved!
